@startuml Profils spécifiques des filières mécanique
' UVs
' Automne 2019 - Connaissances scientifiques
object AC01 {
    分数 = "5"
    简介 = "Révision d'analyse et d'algèbre (apprentissage)"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object AM03 {
    分数 = "4"
    简介 = "Dynamique des solides (apprentissage)"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object AM04 {
    分数 = "5"
    简介 = "Introduction aux propriétés mécaniques des matériaux (apprentissage)"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object AM08 {
    分数 = "4"
    简介 = "Mécanique des fluides incompressibles (apprentissage)"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object AM14 {
    分数 = "5"
    简介 = "Mise en forme des matériaux (apprentissage)"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object EN21 {
    分数 = "6"
    简介 = "Bases de l'électronique analogique"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object MQ01 {
    分数 = "6"
    简介 = "Éléments de résistance des matériaux"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object MQ03 {
    分数 = "6"
    简介 = "Mécanique des vibrations - I"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object IMQ1 {
    分数 = "7"
    简介 = "6Introduction aux propriétés mécaniques et à l'ingénierie des matériaux"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object MT09 {
    分数 = "6"
    简介 = "Analyse numérique"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object MT11 {
    分数 = "6"
    简介 = "Révision d'analyse et d'algèbre"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object MT12 {
    分数 = "6"
    简介 = "Techniques mathématiques pour l'ingénieur"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object NF04 {
    分数 = "6"
    简介 = "Modélisation numérique des problèmes de l'ingénieur"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object SY02 {
    分数 = "7"
    简介 = "Méthodes statistiques pour l'ingénieur"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object SY06 {
    分数 = "6"
    简介 = "Traitement du signal"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object SY08 {
    分数 = "6"
    简介 = "Modélisation des systèmes à évènements discrets"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

object TF01 {
    分数 = "6"
    简介 = "Mécanique des fluides incompressibles"
    季度 = "Automne"
    门类 = "Connaissances scientifiques"
}

' Automne 2019 - Techniques et Méthodes
object AC02 {
    分数 = "4"
    简介 = "Bases de la programmation (apprentissage)"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object AC03 {
    分数 = "4"
    简介 = "Participer à une démarche qualité en entreprise (apprentissage)"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object AM01 {
    分数 = "5"
    简介 = "Modélisation géométrique (apprentissage)"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object AM02 {
    分数 = "6"
    简介 = "Introduction à la conception mécanique (apprentissage)"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object AM15 {
    分数 = "5"
    简介 = "Technologie de fabrication (apprentissage)"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object AM27 {
    分数 = "4"
    简介 = "Capteurs et instrumentation (apprentissage)"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object DI05 {
    分数 = "6"
    简介 = "Méthodologie et analyse de la valeur"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object FQ01 {
    分数 = "6"
    简介 = "Économie globale et maîtrise de la qualité"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object GE37 {
    分数 = "6"
    简介 = "Gestion de projetLO016Bases de la programmation"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object MQ06 {
    分数 = "6"
    简介 = "Modélisation des structures par éléments finis"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object NA18 {
    分数 = "6"
    简介 = "Conception de bases de données relationnelles (autonomie)"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object NF02 {
    分数 = "6"
    简介 = "Du circuit intégré au microprocesseur"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object NF22 {
    分数 = "6"
    简介 = "Micro-ordinateurs et applications"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object PR00 {
    分数 = "5"
    简介 = "Réalisation de projet"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object SY03 {
    分数 = "6"
    简介 = "Introduction aux systèmes d'entraînements électriques"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object SY10 {
    分数 = "6"
    简介 = "Logique floue - concepts et applications"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object TN02 {
    分数 = "6"
    简介 = "Introduction à la conception mécanique"
    季度 = "Automne"
    门类 = "Techniques et Méthodes scientifiques"
}

object TN12 {
    分数 = "6"
    简介 = "Conception mécanique"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object TN20 {
    分数 = "6"
    简介 = "CAO - modélisation géométrique"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object TN22 {
    分数 = "6"
    简介 = "Éléments de bureau d'études"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

object TN23 {
    分数 = "6"
    简介 = "Techniques de fabrication"
    季度 = "Automne"
    门类 = "Techniques et Méthodes"
}

'Printemps 2020 - Connaissances scientifiques
object AC04 {
    分数 = "5"
    简介 = "Méthodes statistiques pour l'ingénieur (apprentissage)"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object AM05 {
    分数 = "5"
    简介 = "Eléments de résistance des matériaux (apprentissage)"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object AM07 {
    分数 = "5"
    简介 = "Bases de l'électronique analogique (apprentissage)"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object AM12 {
    分数 = "4"
    简介 = "Fiabilité et ingénierie robuste de produits (apprentissage)"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object EL01 {
    分数 = "6"
    简介 = "Phénomènes électromagnétiques"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object EN21 {
    分数 = "6"
    简介 = "Bases de l'électronique analogique"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object MQ01 {
    分数 = "6"
    简介 = "Éléments de résistance des matériaux"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object MQ02 {
    分数 = "6"
    简介 = "Mécanique des solides déformables"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object MQ03 {
    分数 = "6"
    简介 = "Mécanique des vibrations - I"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object IMQ1 {
    分数 = "7"
    简介 = "6Introduction aux propriétés mécaniques et à l'ingénierie des matériaux"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object MQ18 {
    分数 = "6"
    简介 = "Cinématique et dynamique des systèmes"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object MT11 {
    分数 = "6"
    简介 = "Révision d'analyse et d'algèbre"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object MT12 {
    分数 = "6"
    简介 = "Techniques mathématiques pour l'ingénieur"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object NF04 {
    分数 = "6"
    简介 = "Modélisation numérique des problèmes de l'ingénieur"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object SY02 {
    分数 = "7"
    简介 = "Méthodes statistiques pour l'ingénieur"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object SY04 {
    分数 = "6"
    简介 = "Systèmes asservis linéaires - analyse et commande"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object SY06 {
    分数 = "6"
    简介 = "Traitement du signal"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object TF01 {
    分数 = "6"
    简介 = "Mécanique des fluides incompressibles"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

object TF06 {
    分数 = "6"
    简介 = "Transfert de chaleur"
    季度 = "Printemps"
    门类 = "Connaissances scientifiques"
}

'Printemps 2020 - Techniques et Méthodes
object AM06 {
    分数 = "6"
    简介 = "Conception mécanique niveau 1 (apprentissage)"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object AM09 {
    分数 = "4"
    简介 = "Excellence industrielle et lean management (apprentissage)"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object AM10 {
    分数 = "5"
    简介 = "Introduction à la pratique de l'acoustique"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object AM35 {
    分数 = "5"
    简介 = "Fabrication assistée par ordinateur et machines à commande numérique (apprentissage)"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object CT04 {
    分数 = "6"
    简介 = "Contrôles non destructifs"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object DD02 {
    分数 = "6"
    简介 = "Ecoconception des systèmes"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object DI05 {
    分数 = "6"
    简介 = "Méthodologie et analyse de la valeur"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object EL02 {
    分数 = "6"
    简介 = "Électricité industrielle appliquée"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object FQ01 {
    分数 = "6"
    简介 = "Économie globale et maîtrise de la qualité"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object GE37 {
    分数 = "6"
    简介 = "Gestion de projetLO016Bases de la programmation"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object MC05 {
    分数 = "6"
    简介 = "Machines de transfert de fluides"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object MQ06 {
    分数 = "6"
    简介 = "Modélisation des structures par éléments finis"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object MQ09 {
    分数 = "6"
    简介 = "Vibrations des systèmes continus"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object MQ11 {
    分数 = "6"
    简介 = "Mise en œuvre des matériaux"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object NA18 {
    分数 = "6"
    简介 = "Conception de bases de données relationnelles (autonomie)"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object NF02 {
    分数 = "6"
    简介 = "Du circuit intégré au microprocesseur"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object NF18 {
    分数 = "6"
    简介 = "Conception de bases de données relationnelles"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object NF22 {
    分数 = "6"
    简介 = "Micro-ordinateurs et applicationsPR005Réalisation de projet"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object PS09 {
    分数 = "6"
    简介 = "Introduction à la pratique de l'acoustique"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object TN02 {
    分数 = "6"
    简介 = "Introduction à la conception mécanique"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object TN12 {
    分数 = "6"
    简介 = "Conception mécanique"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object TN20 {
    分数 = "6"
    简介 = "CAO - modélisation géométrique"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object TN22 {
    分数 = "6"
    简介 = "Éléments de bureau d'études"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object TN29 {
    分数 = "6"
    简介 = "Outils de définition et de développement de systèmes"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

object TN30 {
    分数 = "3"
    简介 = "Séminaires sur la transformation numérique pour l'ingénierie mécanique"
    季度 = "Printemps"
    门类 = "Techniques et Méthodes"
}

