@startuml Profils spécifiques des filières mécanique

skinparam arrowThickness 3
skinparam nodesep 50
skinparam ranksep 200

note "A 代表秋季" as N1
note "P 代表春季" as N2
note "TM 为 Techniques et Méthodes" as N3
note "CS 为 Connaissances scientifiques" as N4

' Filières
object AVI #Red {
    Acoustique et vibrations pour l'ingénieur
}

object CMI #Blue {
    Conception mécanique intégrée
}

object FQI #Yellow {
    Fiabilité et qualité industrielle
}

object IDI #Green {
    Ingénierie du design industriel
}

object MARS #Violet {
    Mécatronique, actionneurs, robotisation et systèmes
}

object MIT #Orange {
    Matériaux et innovation technologique
}

object PIL #Crimson {
    Production intégrée et logistique
}

object SIM #Orchid {
    Simulation pour l’ingénierie mécanique
}

object MPI #Teal {
    Management de projets innovants
}

'UVs

object SY06
object PS09
object NF04
object MQ01
object PS22
object SY03
object DI05
object SY04
object EN21
object EL02
object GE37
object DI01
object DI02
object MQ17
object MT23
object MT90
object MC03
object MC04
object SY01
object SY02
object GE25
object TN01
object TN03
object PS21
object TN20
object TN06
object MQ03
object BL40
object PS91
object TN22

object TN02
TN01 <|-- TN02
TN03 <|-- TN02 : conseillé

object PS04
MT90 <|-- PS04

object PS94
MT90 <|-- PS94

object MQ02
MQ01 <|-- MQ02

object MQ06
MQ01 <|-- MQ06 : ou MQ02
' MQ02 <|-- MQ06 : ou MQ01

object MQ18
PS21 <|-- MQ18
TN06 <|-- MQ18
PS22 <|-- MQ18

' object MQ01
TN06 <|-- MQ01
PS91 <|-- MQ01

object TN12
TN02 <|-- TN12 : (TN03-TN06-MQ01) ou TN22
TN22 <|-- TN12 : (TN23-MQ01) ou TN02

object MC05
PS04 <|-- MC05

' object EL02
PS94 <|-- EL02
MT23 <|-- EL02

object BM07
MQ17 <|-- BM07
BL40 <|-- BM07

'Automne 2019 - Techniques et Méthodes
object AM23 {
    6 A TM
}

object AP51 {
    8 A TM
}

MQ10 <|-- AP51 #Black
TN12 <|-- AP51 #Black
TN13 <|-- AP51 #Black
' TN20 <|-- AP51 #Black

MS02 <|-- AP51 #Black
SY04 <|-- AP51 #Black
SY03 <|-- AP51 #Black
GE37 <|-- AP51 #Black
MQ03 <|-- AP51 #Black
MQ18 <|-- AP51 #Black
MQ06 <|-- AP51 #Black
TN21 <|-- AP51 #Black
TN14 <|-- AP51 #Black
DI05 <|-- AP51 #Black

object AP52 {
    8 A TM
}

MQ01 <|-- AP52
MQ02 <|-- AP52
MQ06 <|-- AP52

MQ16 --  AP52
MQ19 --  AP52
MQ14 --  AP52
BM08 --  AP52

object AP53 {
    8 A TM
}

object CF04 {
    6 A TM
}

object DI04 {
    6 A TM
}

' DI02 <|-- DI04
DI03 <|-- DI04
TN08 <|-- DI04

object DI08 {
    6 A TM
}

TN08 <|-- DI08
DI03 <|-- DI08
EG01 <|-- DI08

object FQ03 {
    6 A TM
}

object FQ07 {
    6 A TM
}

SY01 <|-- FQ07
SY02 <|-- FQ07
FQ05 <|-- FQ07 : conseillé

object GE38 {
    6 A TM
}

object GE39 {
    6 A TM
}

object GE40 {
    6 A TM
}

GE37 <|-- GE40

object MC02 {
    6 A TM
}

object MC06 {
    6 A TM
}

SY04 <|-- MC06

object MC08 {
    6 A TM
}

MC01 <|-- MC08 #SkyBlue
MC02 <|-- MC08 #SkyBlue
MC03 <|-- MC08 #SkyBlue
MC04 <|-- MC08 #SkyBlue
MC05 <|-- MC08 #SkyBlue
MC06 <|-- MC08 #SkyBlue
MC07 <|-- MC08 #SkyBlue

object MP03 {
    6 A TM
}

object MQ05 {
    6 A TM
}

object MQ07 {
    6 A TM
}

BM07 <|-- MQ07

object MQ12 {
    6 A TM
}

object MQ13 {
    6 A TM
}

object MQ16 {
    6 A TM
}

MQ02 <|-- MQ16 #DarkBlue
NF04 <|-- MQ16 #DarkBlue
MQ06 <|-- MQ16 #DarkBlue

object MS03 {
    6 A TM
}

PS09 <|-- MS03
MQ03 <|-- MS03
SY06 <|-- MS03

object PR00 {
    5 A TM
}

object PS12 {
    6 A TM
}

PS09 <|-- PS12 #Green
NF04 <|-- PS12 #Green

object PS13 {
    6 A TM
}

PS09 <|-- PS13 #DeepSkyBlue
NF04 <|-- PS13 #DeepSkyBlue

object TN08 {
    6 A TM
}

object TN14 {
    6 A TM
}

TN12 <|-- TN14
TN13 <|-- TN14
SY04 <|-- TN14

object TN21 {
    6 A TM
}

TN20 <|-- TN21
TN12 <|-- TN21

object TX00 {
    5 A TM
}

'Printemps 2020  - Connaissances scientifiques
object MC01 {
    6 P CS
}

object PS05 {
    6 P CS
}

MQ03 <|-- PS05 #Yellow
PS09 <|-- PS05 #Yellow

object SY09 {
    6 P CS
}

SY02 <|-- SY09

'Printemps 2020  - Techniques et Méthodes
object BM08 {
    5 P TM
}

object BZ08 {
    5 P TM
}

object CT02 {
    6 P TM
}

object DI03 {
    6 P TM
}

DI01 <|-- DI03 : ou DI02
DI02 <|-- DI03

object DI06 {
    6 P TM
}

object EG01 {
    6 P TM
}

object EN14 {
    6 P TM
}

EN21 <|-- EG01

object FQ05 {
    6 P TM
}

object MC07 {
    6 P TM
}

EN21 <|-- MC07
EL02 <|-- MC07

object MP02 {
    6 P TM
}

GE25 <|-- MP02

object MQ04 {
    6 P TM
}

object MQ08 {
    6 P TM
}

MQ17 <|-- MQ08

object MQ10 {
    6 P TM
}

MQ17 -- MQ10 #DarkOliveGreen : conseillé
MQ02 -- MQ10 #DarkOliveGreen : conseillé

object MQ14 {
    6 P TM
}

object MQ19 {
    6 P TM
}

MQ03 <|-- MQ19 #YellowGreen
MQ06 <|-- MQ19 #YellowGreen : ou NF04
NF04 <|-- MQ19 #YellowGreen : ou MQ06
MQ01 <|-- MQ19 #YellowGreen
MQ02 <|-- MQ19 #YellowGreen

object MS02 {
    6 P TM
}

EN21 <|-- MS02 : conseillé mais pas obligatoire

object NF15 {
    6 P TM
}

object SY12 {
    6 P TM
}

object TN13 {
    6 P TM
}

MQ01 <|-- TN13 #OrangeRed
MQ03 <|-- TN13 #OrangeRed : ou MQ18 fortement conseillée
MQ18 <|-- TN13 #OrangeRed : ou MQ03 fortement conseillée
NF04 <|-- TN13 #OrangeRed : ou MQ06 conseillée
MQ06 <|-- TN13 #OrangeRed : ou NF04 conseillée
TN12 <|-- TN13 #OrangeRed : conseillée

object TN24 {
    6 P TM
}

'依赖关系
'AVI
MS03 *-- AVI #Red
PS12 *-- AVI #Red
PS13 *-- AVI #Red
PS05 *-- AVI #Red
MQ19 *-- AVI #Red

'CMI
AP51 *-- CMI #Blue
MQ05 *-- CMI #Blue
TN14 *-- CMI #Blue
TN21 *-- CMI #Blue
MS02 *-- CMI #Blue
TN13 *-- CMI #Blue
TN24 *-- CMI #Blue

'FQI
EG01 *-- FQI #Yellow
FQ03 *-- FQI #Yellow
FQ07 *-- FQI #Yellow
MQ05 *-- FQI #Yellow
SY09 *-- FQI #Yellow
CT02 *-- FQI #Yellow
FQ05 *-- FQI #Yellow

'IDI
DI04 *-- IDI #Green
DI08 *-- IDI #Green
EG01 *-- IDI #Green
MQ12 *-- IDI #Green
TN08 *-- IDI #Green
DI03 *-- IDI #Green
DI06 *-- IDI #Green

'MARS
MC02 *-- MARS #Violet
MC06 *-- MARS #Violet
MC08 *-- MARS #Violet
MC01 *-- MARS #Violet
EN14 *-- MARS #Violet
MC07 *-- MARS #Violet
NF15 *-- MARS #Violet

'MIT
MQ05 *-- MIT #Orange
MQ07 *-- MIT #Orange
MQ12 *-- MIT #Orange
MQ13 *-- MIT #Orange
MQ04 *-- MIT #Orange
MQ08 *-- MIT #Orange
MQ10 *-- MIT #Orange

'MPI
TX00 *-- MPI #Teal
PR00 *-- MPI #Teal
GE38 *-- MPI #Teal
GE39 *-- MPI #Teal
GE40 *-- MPI #Teal

'PIL
AM23 *-- PIL #Crimson
AP53 *-- PIL #Crimson
MP03 *-- PIL #Crimson
CT02 *-- PIL #Crimson
FQ05 *-- PIL #Crimson
MP02 *-- PIL #Crimson
MS02 *-- PIL #Crimson
SY12 *-- PIL #Crimson
TN24 *-- PIL #Crimson

'SIM
MQ19 *-- SIM #Orchid
MQ14 *-- SIM #Orchid
BZ08 *-- SIM #Orchid
BM08 *-- SIM #Orchid
MQ16 *-- SIM #Orchid
MQ13 *-- SIM #Orchid
CF04 *-- SIM #Orchid
AP52 *-- SIM #Orchid

@enduml