@startuml Profils spécifiques des filières mécanique
' Classe
object TM {
    Techniques et Méthodes
}

object CS {
    Connaissances scientifiques
}

object Printemps
object Automne

' Filières
object AVI {
    Acoustique et vibrations pour l'ingénieur
}

object CMI {
    Conception mécanique intégrée
}

object FQI {
    Fiabilité et qualité industrielle
}

object IDI {
    Ingénierie du design industriel
}

object MARS {
    Mécatronique, actionneurs, robotisation et systèmes
}

object MIT {
    Matériaux et innovation technologique
}

object PIL {
    Production intégrée et logistique
}

object SIM {
    Simulation pour l’ingénierie mécanique
}

object MPI {
    Management de projets innovants
}

'UVs
object AM23 {
    Système de production et usine numérique (apprentissage)
    6
}

object AP51 {
    Atelier projet conception mécaniqueintégrée
    8
}

object AP52 {
    Modélisation - optimisation desproduits et structures
    8
}



object AP53 {
    Production intégrée et logistique
    8
}

object CF04 {
    Mécanique des fluides numérique etcouplages multiphysiques
    6

}

object DI04 {
    Design packaging
    6

}

object DI08 {
    Design industriel et création deproduits
    6

}

object EG01 {
    Ergonomie
    6

}

object FQ03 {
    Conception robuste et plansd'expériences
    6

}

object FQ07 {
    Stratégie de maintenance industrielle
    6

}

object GE38 {
    Management et outils d'aide à lacréativité industrielle et à l'innovation
    6

}

object GE39 {
    Management et marketing del'innovation
    6

}

object GE40 {
    Management de projets
    6

}

object MC02 {
    Entraînements électriques à vitessevariable
    6

}

object MC06 {
    Modélisation, dimensionnement,réglages d'axes électromécaniques
    6

}

object MC08 {
    Ingénierie robotique et actionneursélectriques
    6

}

object MP03 {
    Supply chain management (Gestion dela chaîne logistique)
    6

}

object MQ05 {
    Tribologie
    6

}

object MQ07 {
    Matériaux pour applications hautestempératures
    6

}

object MQ12 {
    Choix des matériaux et des procédés
    6

}

object MQ13 {
    Matériaux composites
    6

}

object MQ16 {
    Éléments finis pour la modélisation decrash et l'analyse d'impacts
    6

}

object MS03 {
    Atelier projet en acoustique etvibrations
    6

}

object PR00 {
    Réalisation de projet
    5

}

object PS12 {
    Acoustique des salles : matériaux etmodélisation
    6

}

object PS13 {
    Simulation numérique envibroacoustique
    6

}

object TN08 {
    Dessin de communication
    6

}

object TN14 {
    Commande hydraulique de puissance
    6

}

object TN21 {
    Gestion du cycle de vie du produit etingénierie collaborative
    6

}

object TX00 {
    Étude expérimentale
    5

}

'Printemps 2020  - Connaissances scientifiques
object MC01 {
    Machines électriques
    6

}

object PS05 {
    Acoustique physique : sourcessonores et propagation
    6

}

object SY09 {
    Analyse de données et data mining
    6

}

'Printemps 2020  - Techniques et Méthodes
object BM08 {
    Modélisation des systèmes biomécaniques
    5

}

object BZ08 {
    Modélisation des systèmes biomécaniques
    5

}

object CT02 {
    Maîtrise statistique des processus
    6

}

object DI03 {
    Conception formelle des produits
    6

}

object DI06 {
    Analyse des produits deconsommation
    6

}

object EG01 {
    Ergonomie
    6

}

object EN14 {
    Fonctions électroniques pourl'ingénieur
    6

}

object FQ05 {
    Fiabilité industrielle
    6

}

object GE38 {
    Management et outils d'aide à lacréativité industrielle et à l'innovation
    6

}

object GE39 {
    Management et marketing del'innovation
    6

}

object MC07 {
    Électronique de puissance
    6

}

object MP02 {
    Introduction aux méthodes de la GPAO
    6

}

object MQ04 {
    Polymères
    6

}

object MQ08 {
    Élaboration et propriétés d'usage desmétaux
    6

}

object MQ10 {
    Comportement mécanique desmatériaux
    6

}

object MQ14 {
    Optimisation en mécanique
    6

}

object MQ19 {
    Dynamique des structures
    6

}

object MS02 {
    Principes physiques des capteurs etinstrumentation
    6

}

object MS03 {
    Atelier projet en acoustique etvibrations
    6

}

object NF15 {
    Microprocesseurs, interfaces etlogiciels de base
    6

}

object PR00 {
    Réalisation de projet
    5

}

object SY12 {
    简介=" Modélisation et performance dessystèmes de production"
    分数="6"

}
object TN08 {
    Dessin de communication
    6

}

object TN13 {
    Dimensionnement pour la conceptiondes systèmes mécaniques
    6

}

object TN24 {
    Technologies de fabrication et outilsméthodes
    6

}

object TX00 {
    Étude expérimentale
    5

}

'学期

Automne *-- AM23
Automne *-- AP51
Automne *-- AP52
Automne *-- AP53
Automne *-- CF04
Automne *-- DI04
Automne *-- DI08
Automne *-- EG01
Automne *-- FQ03
Automne *-- FQ07
Automne *-- GE38
Automne *-- GE39
Automne *-- GE40
Automne *-- MC02
Automne *-- MC06
Automne *-- MC08
Automne *-- MP03
Automne *-- MQ05
Automne *-- MQ07
Automne *-- MQ12
Automne *-- MQ13
Automne *-- MQ16
Automne *-- MS03
Automne *-- PR00
Automne *-- PS12
Automne *-- PS13

'种类
TM *-- AM23
TM *-- AP51
TM *-- AP52
TM *-- AP53
TM *-- CF04
TM *-- DI04
TM *-- DI08
TM *-- EG01
TM *-- FQ03
TM *-- FQ07
TM *-- GE38
TM *-- GE39
TM *-- GE40
TM *-- MC02
TM *-- MC06
TM *-- MC08
TM *-- MP03
TM *-- MQ05
TM *-- MQ07
TM *-- MQ12
TM *-- MQ13
TM *-- MQ16
TM *-- MS03
TM *-- PR00
TM *-- PS12
TM *-- PS13

'依赖关系
'AVI
MS03 *-- AVI
PS12 *-- AVI
PS13 *-- AVI
PS05 *-- AVI
MQ19 *-- AVI
MS03 *-- AVI

'CMI
AP51 *-- CMI
MQ05 *-- CMI
TN14 *-- CMI
TN21 *-- CMI
MS02 *-- CMI
TN13 *-- CMI
TN24 *-- CMI

'FQI
EG01 *-- FQI
FQ03 *-- FQI
FQ07 *-- FQI
MQ05 *-- FQI
SY09 *-- FQI
CT02 *-- FQI
EG01 *-- FQI
FQ05 *-- FQI

'IDI
DI04 *-- IDI
DI08 *-- IDI
EG01 *-- IDI
MQ12 *-- IDI
TN08 *-- IDI
DI03 *-- IDI
DI06 *-- IDI
EG01 *-- IDI
TN08 *-- IDI

'MARS
MC02 *-- MARS
MC06 *-- MARS
MC08 *-- MARS
MC01 *-- MARS
EN14 *-- MARS
MC07 *-- MARS
NF15 *-- MARS

'MIT
MQ05 *-- MIT
MQ07 *-- MIT
MQ12 *-- MIT
MQ13 *-- MIT
MQ04 *-- MIT
MQ08 *-- MIT
MQ10 *-- MIT

'MPI
TX00 *-- MPI
PR00 *-- MPI
GE39 *-- MPI
GE38 *-- MPI
TX00 *-- MPI
GE38 *-- MPI
GE39 *-- MPI
GE40 *-- MPI
PR00 *-- MPI

'PIL
AM23 *-- PIL
AP53 *-- PIL
MP03 *-- PIL
CT02 *-- PIL
FQ05 *-- PIL
MP02 *-- PIL
MS02 *-- PIL
SY12 *-- PIL
TN24 *-- PIL

'SIM
MQ19 *-- SIM
MQ14 *-- SIM
BZ08 *-- SIM
BM08 *-- SIM
MQ16 *-- SIM
MQ13 *-- SIM
CF04 *-- SIM
AP52 *-- SIM

@enduml